import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Noto_Sans_Thai } from "next/font/google";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const noto_san_thai = Noto_Sans_Thai({ subsets: ["latin"], display: "swap" });

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body
        className={noto_san_thai.className}
      >
        {children}
      </body>
    </html>
  );
}
